from typing import Protocol

from .models import Task, User


class UserRepository(Protocol):
    def by_email(self, email: str) -> User | None: ...
    def add(self, email: str, password_hash: str) -> User: ...


class TaskRepository(Protocol):
    def list_for_user(self, user_id: int) -> list[Task]: ...
    def by_id_for_user(self, task_id: int, user_id: int) -> Task | None: ...
    def add(self, user_id: int, title: str, description: str | None) -> Task: ...
    def set_done(self, task_id: int, user_id: int, is_done: bool) -> Task | None: ...
    def delete(self, task_id: int, user_id: int) -> bool: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, stored: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue(self, user_id: int) -> str: ...
